window.ETHNOGRAPHY_BOOKS = [
  {
    "id": "ethnography-01",
    "title": "《维塔》(Vita)",
    "year": 2005,
    "author": "João Biehl",
    "publisher": "Princeton",
    "summary": "追踪巴西收容机构中被遗弃的精神病患者，以一名女性的生命为核心线索。\n\n结合长期田野、照片民族志与档案追溯。\n\n国家与家庭共谋将无用之人逐入遗弃区。",
    "location": "Porto Alegre",
    "countryOrRegion": "Brazil",
    "lat": -30.0346,
    "lon": -51.2177,
    "sourceField": "巴西 - 阿雷格里港",
    "locationEn": "Brazil · Porto Alegre"
  },
  {
    "id": "ethnography-02",
    "title": "《多重身体》(The Body Multiple)",
    "year": 2002,
    "author": "Annemarie Mol",
    "publisher": "Duke",
    "summary": "同一疾病在荷兰医院不同实践场景中呈现为多种截然不同的现实。\n\n跟踪检查、手术室、门诊等日常医学实践。\n\n疾病不是被发现的，而是在不同实践中被多元地制造出来的。",
    "location": "Utrecht",
    "countryOrRegion": "Netherlands",
    "lat": 52.0907,
    "lon": 5.1214,
    "sourceField": "荷兰 - 乌得勒支",
    "locationEn": "Netherlands · Utrecht"
  },
  {
    "id": "ethnography-03",
    "title": "《暴露下的生命》(Life Exposed)",
    "year": 2002,
    "author": "Adriana Petryna",
    "publisher": "Princeton",
    "summary": "切尔诺贝利核灾后，乌克兰人以受损的身体换取国家补偿与公民权利。\n\n基辅及灾区田野调查结合政策文件研究。\n\n受苦的身体成为政治谈判资本，催生后苏联时代的新型公民身份。",
    "location": "Kyiv / Chernobyl Region",
    "countryOrRegion": "Ukraine",
    "lat": 50.2,
    "lon": 30.3,
    "sourceField": "乌克兰 - 基辅/切尔诺贝利区域",
    "locationEn": "Ukraine · Kyiv / Chernobyl region"
  },
  {
    "id": "ethnography-04",
    "title": "《即兴医疗》(Improvising Medicine)",
    "year": 2012,
    "author": "Julie Livingston",
    "publisher": "Duke",
    "summary": "博茨瓦纳唯一癌症病房中的照护、生死处置与医护伦理。\n\n长期病房民族志与患者及医护人员访谈。\n\n资源匮乏催生医疗即兴，既揭示全球卫生不平等，也彰显照护者的伦理创造力。",
    "location": "Gaborone",
    "countryOrRegion": "Botswana",
    "lat": -24.6282,
    "lon": 25.9231,
    "sourceField": "博茨瓦纳 - 哈博罗内",
    "locationEn": "Botswana · Gaborone"
  },
  {
    "id": "ethnography-05",
    "title": "《治疗共和国》(The Republic of Therapy)",
    "year": 2010,
    "author": "Vinh-Kim Nguyen",
    "publisher": "Duke",
    "summary": "西非艾滋病危机中，抗病毒药物的稀缺分配如何重塑患者的身份与主体性。\n\n布基纳法索与科特迪瓦多地田野调查。\n\n获得治疗的机会制造了新型生命政治身份，药物分配即政治分配。",
    "location": "Burkina Faso / Cote d'Ivoire",
    "countryOrRegion": "West Africa",
    "lat": 10.5,
    "lon": -4.5,
    "sourceField": "西非 - 布基纳法索/科特迪瓦",
    "locationEn": "West Africa · Burkina Faso / Côte d'Ivoire"
  },
  {
    "id": "ethnography-06",
    "title": "《乡间诊所》(The Pastoral Clinic)",
    "year": 2010,
    "author": "Angela Garcia",
    "publisher": "UC Press",
    "summary": "新墨西哥州西裔社区代际传承的海洛因成瘾与难以言说的悲恸。\n\n埃斯帕诺拉河谷长期田野调查与家庭访谈。\n\n成瘾根植于土地丧失与历史创伤，是悲恸的身体表达，而非个人道德缺陷。",
    "location": "Espanola Valley, New Mexico",
    "countryOrRegion": "United States",
    "lat": 36.0,
    "lon": -106.1,
    "sourceField": "美国 - 新墨西哥州 埃斯帕诺拉河谷",
    "locationEn": "United States · Española Valley, New Mexico"
  },
  {
    "id": "ethnography-07",
    "title": "《债中生活》(Life in Debt)",
    "year": 2012,
    "author": "Clara Han",
    "publisher": "UC Press",
    "summary": "圣地亚哥贫困社区在新自由主义改革下的债务、照护与亲密关系。\n\n长期社区民族志，深入家庭日常。\n\n债务渗透底层的伦理互助，重塑亲属间的依存关系，使照护本身成为负重的实践。",
    "location": "Santiago",
    "countryOrRegion": "Chile",
    "lat": -33.4489,
    "lon": -70.6693,
    "sourceField": "智利 - 圣地亚哥",
    "locationEn": "Chile · Santiago"
  },
  {
    "id": "ethnography-08",
    "title": "《新鲜的水果，破碎的身体》(Fresh Fruit, Broken Bodies)",
    "year": 2013,
    "author": "Seth Holmes",
    "publisher": "UC Press",
    "summary": "墨西哥移民农工在美国的迁徙、劳动与身体受苦。\n\n亲身随工人下地务农的参与式观察。\n\n结构性暴力与种族化将不平等铭刻于工人身体，并将他们的痛苦自然化、正常化。",
    "location": "Oaxaca",
    "countryOrRegion": "Mexico / United States",
    "lat": 17.0732,
    "lon": -96.7266,
    "sourceField": "美国(华盛顿州)-墨西哥(瓦哈卡)",
    "locationEn": "United States (Washington State) · Mexico (Oaxaca)",
    "sites": [
      {
        "lat": 48.4193,
        "lon": -122.3349
      },
      {
        "lat": 17.0732,
        "lon": -96.7266
      }
    ]
  },
  {
    "id": "ethnography-09",
    "title": "《权力的病理学》(Pathologies of Power)",
    "year": 2003,
    "author": "Paul Farmer",
    "publisher": "UC Press",
    "summary": "全球贫富不平等如何系统性地剥夺海地、秘鲁等地人群的健康权利。\n\n多地临床田野调查与跨学科批判分析。\n\n结构性暴力是疾病的根源；健康即人权，医学人类学必须直面社会不正义。",
    "location": "Multi-sited: Haiti/Peru/Russia/Cuba",
    "countryOrRegion": "Global Multi-site",
    "lat": 19.0,
    "lon": -72.3,
    "sourceField": "海地、秘鲁、俄罗斯、古巴",
    "locationEn": "Haiti · Peru · Russia · Cuba",
    "sites": [
      {
        "lat": 18.5944,
        "lon": -72.3074
      },
      {
        "lat": -12.0464,
        "lon": -77.0428
      },
      {
        "lat": 55.7558,
        "lon": 37.6173
      },
      {
        "lat": 23.1136,
        "lon": -82.3666
      }
    ]
  },
  {
    "id": "ethnography-10",
    "title": "《两度死亡》(Twice Dead)",
    "year": 2002,
    "author": "Margaret Lock",
    "publisher": "UC Press",
    "summary": "脑死亡定义与器官移植在日本与北美引发的截然不同的认知与争议。\n\n跨文化比较民族志与医学史研究。\n\n死亡是社会建构而非生物事实；文化的局部知识塑造了不同的身体政治。",
    "location": "Tokyo / Montreal",
    "countryOrRegion": "Japan / North America",
    "lat": 35.6762,
    "lon": 139.6503,
    "sourceField": "日本 - 东京 / 北美 - 蒙特利尔等",
    "locationEn": "Japan · Tokyo / North America · Montreal (and environs)",
    "sites": [
      {
        "lat": 35.6762,
        "lon": 139.6503
      },
      {
        "lat": 45.5019,
        "lon": -73.5674
      }
    ]
  },
  {
    "id": "ethnography-11",
    "title": "《末日松茸》(The Mushroom at the End of the World)",
    "year": 2015,
    "author": "Anna Tsing",
    "publisher": "Princeton",
    "summary": "松茸商品链串联美国、日本、中国、芬兰的劳动、生态与多物种关系。\n\n多点田野调查，追踪松茸从森林到市场的全程。\n\n在资本主义废墟中，非正规合作与多物种共存仍可孕育生机，挑战线性进步叙事。",
    "location": "Oregon-Japan-China-Finland Network",
    "countryOrRegion": "Transnational",
    "lat": 44.0582,
    "lon": -121.3153,
    "sourceField": "美国(俄勒冈)-日本-中国-芬兰",
    "locationEn": "United States (Oregon) · Japan · China · Finland"
  },
  {
    "id": "ethnography-12",
    "title": "《森林如何思考》(How Forests Think)",
    "year": 2013,
    "author": "Eduardo Kohn",
    "publisher": "UC Press",
    "summary": "厄瓜多尔卢纳人与亚马逊森林之间的符号互动与跨物种共处方式。\n\n阿维拉社区长期田野调查，结合皮尔斯符号学理论。\n\n符号与思考超越人类边界；森林本身是自我组织的符号过程，呼唤超越人类的人类学。",
    "location": "Avila, Ecuadorian Amazon",
    "countryOrRegion": "Ecuador",
    "lat": -0.67,
    "lon": -77.72,
    "sourceField": "厄瓜多尔 - 阿维拉",
    "locationEn": "Ecuador · Ávila"
  },
  {
    "id": "ethnography-13",
    "title": "《在棕榈树的阴影下》(In the Shadow of the Palms)",
    "year": 2022,
    "author": "Sophie Chao",
    "publisher": "Duke",
    "summary": "油棕种植园扩张对印尼西巴布亚马林德人多物种世界的系统性摧毁。\n\n社区民族志与多物种田野考察。\n\n工业农业造成存在性灾难：不仅是生态危机，更是本体论意义上的世界终结与哀悼。",
    "location": "West Papua, Maro River Region",
    "countryOrRegion": "Indonesia",
    "lat": -8.49,
    "lon": 140.39,
    "sourceField": "印尼 - 西巴布亚 莫劳河区域",
    "locationEn": "Indonesia · West Papua, Maro River Region"
  },
  {
    "id": "ethnography-14",
    "title": "《飞行之路》(Flight Ways)",
    "year": 2014,
    "author": "Thom van Dooren",
    "publisher": "Columbia",
    "summary": "濒危鸟类的灭绝过程、保育劳动及其引发的伦理困境。\n\n跟随保育工作者与鸟类的多地民族志。\n\n灭绝是世代延续的生活方式之终结；哀悼与伦理责任是回应物种消失的恰当姿态。",
    "location": "Hawaii & Australia Flyways",
    "countryOrRegion": "Pacific Region",
    "lat": 21.3069,
    "lon": -157.8583,
    "sourceField": "澳大利亚、美国(夏威夷)",
    "locationEn": "Australia · United States (Hawaii)",
    "sites": [
      {
        "lat": 21.3069,
        "lon": -157.8583
      },
      {
        "lat": -33.8688,
        "lon": 151.2093
      }
    ]
  },
  {
    "id": "ethnography-15",
    "title": "《动物亲缘》(Animal Intimacies)",
    "year": 2018,
    "author": "R. Govindrajan",
    "publisher": "Chicago",
    "summary": "印度库曼山区人与动物间的情感、献祭与日常共处关系。\n\n社区参与观察与深度访谈。\n\n人与动物通过照料与暴力建立亲缘；跨物种关系挑战人类中心主义的亲密边界。",
    "location": "Kumaon Himalaya",
    "countryOrRegion": "India",
    "lat": 29.6,
    "lon": 79.6,
    "sourceField": "印度 - 库曼山区",
    "locationEn": "India · Kumaon Himalaya"
  },
  {
    "id": "ethnography-16",
    "title": "《猪肉城》(Porkopolis)",
    "year": 2020,
    "author": "Alex Blanchette",
    "publisher": "Duke",
    "summary": "美国中西部工业猪肉生产中人与猪如何共同被纳入资本主义生产流水线。\n\n在屠宰场长期从业的深度参与民族志。\n\n工业单一文化将猪的生物节律强加于人类劳动，人与动物一同被化约为生产单元。",
    "location": "U.S. Midwest (Nebraska)",
    "countryOrRegion": "United States",
    "lat": 41.5,
    "lon": -99.8,
    "sourceField": "美国 - 中西部（内布拉斯加州等）",
    "locationEn": "United States · Midwest (Nebraska, etc.)"
  },
  {
    "id": "ethnography-17",
    "title": "《异星海洋》(Alien Ocean)",
    "year": 2009,
    "author": "Stefan Helmreich",
    "publisher": "UC Press",
    "summary": "海洋微生物学家对深海生命边界的科学探索与认知建构。\n\n实验室与科考船田野调查。\n\n深海微生物挑战关于生命与自然的既有范畴；科学实践与资本共同建构海洋的本体。",
    "location": "Hawaii/California & High Seas",
    "countryOrRegion": "Pacific Ocean",
    "lat": 23.0,
    "lon": -155.0,
    "sourceField": "美国 - 夏威夷/加州实验室及公海",
    "locationEn": "United States · Hawaii / California labs · high seas"
  },
  {
    "id": "ethnography-18",
    "title": "《去殖民化灭绝》(Decolonizing Extinction)",
    "year": 2018,
    "author": "J. S. Parreñas",
    "publisher": "Duke",
    "summary": "马来西亚砂拉越猩猩康复机构中的照护实践、与殖民遗产的纠缠。\n\n机构民族志与工作者深度访谈。\n\n保育工作内嵌于殖民关系；去殖民化需正视照护行为的矛盾性，而非浪漫化救援。",
    "location": "Sarawak",
    "countryOrRegion": "Malaysia",
    "lat": 2.5,
    "lon": 113.5,
    "sourceField": "马来西亚 - 砂拉越",
    "locationEn": "Malaysia · Sarawak"
  },
  {
    "id": "ethnography-19",
    "title": "《与牧群共生》(Living with Herds)",
    "year": 2011,
    "author": "Natasha Fijn",
    "publisher": "Cambridge",
    "summary": "蒙古游牧民与畜群之间的共同演化、日常互动与相互塑造。\n\n与牧民共同生活的长期参与田野调查。\n\n家畜是具有能动性的伙伴；人与动物通过长期共处形成跨物种的关系性社会。",
    "location": "Arkhangai Mountains",
    "countryOrRegion": "Mongolia",
    "lat": 47.7,
    "lon": 101.0,
    "sourceField": "蒙古 - 杭爱山脉",
    "locationEn": "Mongolia · Khangai Mountains (Arkhangai)"
  },
  {
    "id": "ethnography-20",
    "title": "《道德实验室》(Moral Laboratories)",
    "year": 2014,
    "author": "Cheryl Mattingly",
    "publisher": "UC Press",
    "summary": "洛杉矶非裔美国家庭在照护慢性病儿童过程中的日常道德实践。\n\n长期家庭民族志与叙事分析。\n\n伦理是在实验与叙事中生成的实践，而非规则遵循；普通家庭是真实的道德哲学实验室。",
    "location": "Los Angeles",
    "countryOrRegion": "United States",
    "lat": 34.0522,
    "lon": -118.2437,
    "sourceField": "美国 - 洛杉矶",
    "locationEn": "United States · Los Angeles"
  },
  {
    "id": "ethnography-21",
    "title": "《成为罪人》(Becoming Sinners)",
    "year": 2004,
    "author": "Joel Robbins",
    "publisher": "UC Press",
    "summary": "巴布亚新几内亚乌拉普明人皈依基督教后经历的道德与文化深层转型。\n\n部落社区长期田野调查。\n\n文化变迁可以是彻底的断裂；乌拉普明人真诚内化了基督教罪感伦理，而非表面融合。",
    "location": "Urapmin, West Sepik Province",
    "countryOrRegion": "Papua New Guinea",
    "lat": -5.02,
    "lon": 141.57,
    "sourceField": "巴布亚新几内亚 - 乌拉普明部落",
    "locationEn": "Papua New Guinea · Urapmin, West Sepik Province"
  },
  {
    "id": "ethnography-22",
    "title": "《正义的瘾君子》(Righteous Dopefiend)",
    "year": 2009,
    "author": "P. Bourgois",
    "publisher": "UC Press",
    "summary": "旧金山无家可归海洛因成瘾者的日常生存、道德世界与相互照料。\n\n长期田野调查结合黑白照片民族志。\n\n成瘾者在结构性暴力中仍维系道德经济；社会排斥才是成瘾的根源，而非个体失德。",
    "location": "San Francisco",
    "countryOrRegion": "United States",
    "lat": 37.7749,
    "lon": -122.4194,
    "sourceField": "美国 - 旧金山",
    "locationEn": "United States · San Francisco"
  },
  {
    "id": "ethnography-23",
    "title": "《美德的主体》(The Subject of Virtue)",
    "year": 2013,
    "author": "James Laidlaw",
    "publisher": "Cambridge",
    "summary": "印度耆那教苦行者的伦理修行实践与自由概念的人类学反思。\n\n斋浦尔苦行者社群的田野调查。\n\n美德需要自由；伦理不是习惯养成，而是自觉的自我培育，挑战功利主义与共同体主义。",
    "location": "Jaipur, Rajasthan",
    "countryOrRegion": "India",
    "lat": 26.9124,
    "lon": 75.7873,
    "sourceField": "印度 - 拉贾斯坦邦/斋浦尔",
    "locationEn": "India · Rajasthan / Jaipur"
  },
  {
    "id": "ethnography-24",
    "title": "《虔诚的政治》(Politics of Piety)",
    "year": 2005,
    "author": "Saba Mahmood",
    "publisher": "Princeton",
    "summary": "开罗清真寺女性运动中的虔诚实践与伊斯兰伦理主体的形成。\n\n开罗女性清真寺运动的田野调查。\n\n服从与虔诚也是能动性的表达；质疑自由主义女性主义对能动性概念的狭隘预设。",
    "location": "Cairo",
    "countryOrRegion": "Egypt",
    "lat": 30.0444,
    "lon": 31.2357,
    "sourceField": "埃及 - 开罗",
    "locationEn": "Egypt · Cairo"
  },
  {
    "id": "ethnography-25",
    "title": "《生命之侧》(Life Beside Itself)",
    "year": 2014,
    "author": "Lisa Stevenson",
    "publisher": "UC Press",
    "summary": "加拿大因纽特人的自杀危机与国家匿名照护机制的冷漠结构。\n\n努纳武特地区田野调查结合精神分析理论。\n\n国家照护管理生命却忽视灵魂；因纽特人的图像思维揭示另一种生命政治的可能。",
    "location": "Nunavut",
    "countryOrRegion": "Canada",
    "lat": 66.0,
    "lon": -86.0,
    "sourceField": "加拿大 - 努纳武特地区",
    "locationEn": "Canada · Nunavut"
  },
  {
    "id": "ethnography-26",
    "title": "《一心一意》(A Heart for the Work)",
    "year": 2010,
    "author": "Claire Wendland",
    "publisher": "Chicago",
    "summary": "马拉维医学生在资源极度匮乏条件下接受训练并形成医者伦理的过程。\n\n医学院与医院的田野调查。\n\n非洲医学培训塑造独特使命感；医生在匮乏中学会为工作奉献之心。",
    "location": "Blantyre",
    "countryOrRegion": "Malawi",
    "lat": -15.7861,
    "lon": 35.0058,
    "sourceField": "马拉维 - 布兰太尔",
    "locationEn": "Malawi · Blantyre"
  },
  {
    "id": "ethnography-27",
    "title": "《生存的意志》(The Will to Live)",
    "year": 2005,
    "author": "João Biehl",
    "publisher": "Princeton",
    "summary": "巴西艾滋病患者如何通过法律诉讼争取免费药物，以及由此形成的生命政治格局。\n\n田野调查结合法律档案与患者访谈。\n\n生存的意志经由法律与制度化得以实现；巴西艾滋病治疗将药物可及性转化为公民权利。",
    "location": "Salvador & Southern Cities",
    "countryOrRegion": "Brazil",
    "lat": -12.9777,
    "lon": -38.5016,
    "sourceField": "巴西 - 萨尔瓦多/南部城市",
    "locationEn": "Brazil · Salvador / southern Brazilian cities"
  },
  {
    "id": "ethnography-28",
    "title": "《生活与言词》(Life and Words)",
    "year": 2006,
    "author": "Veena Das",
    "publisher": "UC Press",
    "summary": "印度分治暴力与博帕尔灾难在德里贫民窟中留下的创伤记忆与日常承担。\n\n德里社区长期田野调查与深度对话式访谈。\n\n日常生活是消化暴力的场所；降入日常是幸存者在创伤裂缝中重建可居世界的生命实践。",
    "location": "Delhi",
    "countryOrRegion": "India",
    "lat": 28.6139,
    "lon": 77.209,
    "sourceField": "印度 - 德里",
    "locationEn": "India · Delhi"
  },
  {
    "id": "ethnography-30",
    "title": "《坠落的天空》(The Falling Sky)",
    "year": 2013,
    "author": "Davi Kopenawa",
    "publisher": "Harvard",
    "summary": "亚诺马米萨满对本民族宇宙观、森林知识与生存危机的第一人称叙述。\n\n合作完成的自述式民族志，历时数十年。\n\n亚诺马米宇宙观构成对西方商品拜物教的深刻批判；萨满劳作维系着天空与世界。",
    "location": "Amazon Forest (Brazil/Venezuela)",
    "countryOrRegion": "Brazil / Venezuela",
    "lat": 1.0,
    "lon": -63.0,
    "sourceField": "巴西/委内瑞拉 - 亚马逊森林",
    "locationEn": "Brazil / Venezuela · Amazon rainforest"
  },
  {
    "id": "ethnography-31",
    "title": "《大地之灵》(Earth Beings)",
    "year": 2015,
    "author": "M. de la Cadena",
    "publisher": "Duke",
    "summary": "秘鲁安第斯土著政治实践中非人类的大地存在（tirakuna）所扮演的能动角色。\n\n安第斯山区田野调查结合本体论分析。\n\n土著政治纳入了非人类存在；这颠覆了现代民主政治的人类中心主义前提。",
    "location": "Ausangate, Andes",
    "countryOrRegion": "Peru",
    "lat": -13.787,
    "lon": -71.229,
    "sourceField": "秘鲁 - 安第斯山区 奥桑加特山",
    "locationEn": "Peru · Ausangate, Peruvian Andes"
  },
  {
    "id": "ethnography-32",
    "title": "《超越自然与文化》(Beyond Nature and Culture)",
    "year": 2013,
    "author": "Philippe Descola",
    "publisher": "Chicago",
    "summary": "对四种人类与非人类关系模式（泛灵论、图腾主义、类比论、自然主义）的跨文化比较。\n\n泛亚马逊田野调查结合结构分析。\n\n自然与文化的二元对立是西方独有的本体论；泛灵论等其他模式提供了同等有效的世界观。",
    "location": "Ecuadorian Pan-Amazon",
    "countryOrRegion": "Ecuador / Pan-Amazon",
    "lat": -1.5,
    "lon": -76.5,
    "sourceField": "厄瓜多尔、泛亚马逊区域",
    "locationEn": "Ecuador · Pan-Amazon region"
  },
  {
    "id": "ethnography-33",
    "title": "《食人族形而上学》(Cannibal Metaphysics)",
    "year": 2014,
    "author": "E. V. de Castro",
    "publisher": "Univocal",
    "summary": "亚马逊原住民视角主义：所有存在共享文化视角，但拥有各自不同的身体与自然。\n\n比较神话学与跨部落民族志的理论重构。\n\n多自然主义颠覆西方多文化主义；原住民思想应被视为与西方哲学平等的智识传统。",
    "location": "Amazon Basin",
    "countryOrRegion": "Brazil",
    "lat": -3.0,
    "lon": -62.0,
    "sourceField": "巴西 - 亚马逊河流域",
    "locationEn": "Brazil · Amazon Basin"
  },
  {
    "id": "ethnography-34",
    "title": "《运动中的真理》(Truth in Motion)",
    "year": 2012,
    "author": "Martin Holbraad",
    "publisher": "Chicago",
    "summary": "古巴伊法占卜仪式中，神圣粉末与真理之间的本体论关系。\n\n哈瓦那伊法祭司社群的田野调查。\n\n粉末本身即真理而非象征真理；本体论转向要求我们从田野重建人类学分析概念。",
    "location": "Havana",
    "countryOrRegion": "Cuba",
    "lat": 23.1136,
    "lon": -82.3666,
    "sourceField": "古巴 - 哈瓦那",
    "locationEn": "Cuba · Havana"
  },
  {
    "id": "ethnography-35",
    "title": "《为多元宇宙设计》(Designs for the Pluriverse)",
    "year": 2018,
    "author": "Arturo Escobar",
    "publisher": "Duke",
    "summary": "哥伦比亚土著与非裔社区对替代性自治生活方式与去殖民化设计的探索。\n\n参与式行动研究与社区田野调查。\n\n多元宇宙设计对抗全球化的单一世界逻辑；设计可以成为去殖民化的政治认识论实践。",
    "location": "Cauca Valley",
    "countryOrRegion": "Colombia",
    "lat": 2.5,
    "lon": -76.5,
    "sourceField": "哥伦比亚 - 考卡河谷",
    "locationEn": "Colombia · Cauca Valley"
  },
  {
    "id": "ethnography-36",
    "title": "《魂灵猎人》(Soul Hunters)",
    "year": 2007,
    "author": "Rane Willerslev",
    "publisher": "UC Press",
    "summary": "西伯利亚尤卡吉尔猎人的模仿狩猎哲学：通过变成猎物来接近并诱捕它们。\n\n随猎人共同狩猎的深度参与民族志。\n\n猎人须在模仿与保持人性间维持危险平衡；泛灵论不是信仰，而是务实的存在论策略。",
    "location": "Siberia, Yukaghir Region",
    "countryOrRegion": "Russia",
    "lat": 68.7,
    "lon": 153.0,
    "sourceField": "俄罗斯 - 西伯利亚 尤卡吉尔地区",
    "locationEn": "Russia · Yukaghir Region, Siberia"
  },
  {
    "id": "ethnography-37",
    "title": "《现代性的神灵》(Spirits of Modernity)",
    "year": 2005,
    "author": "Harry G. West",
    "publisher": "Chicago",
    "summary": "莫桑比克穆埃达高原马孔德人的巫术话语与现代权力批判。\n\n高原社区田野调查结合政治历史分析。\n\n巫术是批判权力的本土语言；国家暴力与历史变迁通过巫术想象被体验、争议与诠释。",
    "location": "Mueda Plateau",
    "countryOrRegion": "Mozambique",
    "lat": -11.67,
    "lon": 39.56,
    "sourceField": "莫桑比克 - 穆埃达高原",
    "locationEn": "Mozambique · Mueda Plateau"
  },
  {
    "id": "ethnography-38",
    "title": "《美丽的生命政治》(The Biopolitics of Beauty)",
    "year": 2017,
    "author": "Alvaro Jarrín",
    "publisher": "UC Press",
    "summary": "巴西公立医院中的整形手术如何将美丽建构为国家健康目标，揭示其与种族、阶级的历史纠缠。\n\n医院田野调查结合优生学历史档案与患者访谈。\n\n美被理论化为\"情感资本\"；整形手术制造了\"美学公民身份\"，在消解种族焦虑的表象下持续强化阶级与种族等级。",
    "location": "Rio de Janeiro / São Paulo",
    "countryOrRegion": "Brazil",
    "lat": -22.9068,
    "lon": -43.1729,
    "sourceField": "巴西 - 里约热内卢/圣保罗",
    "locationEn": "Brazil · Rio de Janeiro / São Paulo",
    "sites": [
      {
        "lat": -22.9068,
        "lon": -43.1729
      },
      {
        "lat": -23.5505,
        "lon": -46.6333
      }
    ]
  },
  {
    "id": "ethnography-39",
    "title": "《私人生活的变革》(Private Life under Socialism)",
    "year": 2003,
    "author": "Yunxiang Yan",
    "publisher": "Stanford",
    "summary": "后社会主义时代农村礼物交换的衰退与个人情感生活的兴起，揭示私人领域的道德转型。\n\n长期田野调查与深度访谈，追踪1970至1990年代农村伦理变迁。\n\n国家退出与市场进入共同催生中国的个体化进程，个人权利意识在社会主义遗产的断裂处生长。",
    "location": "Heilongjiang, Xiajia Village",
    "countryOrRegion": "China",
    "lat": 46.0,
    "lon": 127.5,
    "sourceField": "中国 - 黑龙江下岬村",
    "locationEn": "China · Heilongjiang, Xiajia Village"
  },
  {
    "id": "ethnography-40",
    "title": "《中国女工》(Made in China)",
    "year": 2005,
    "author": "Pun Ngai",
    "publisher": "Duke",
    "summary": "深圳电子厂流水线上的年轻农村女工如何在全球资本与国家之间被塑造为顺从的劳动主体。\n\n在工厂宿舍长期居住、并于车间与工人并肩工作的深度参与观察。\n\n身体的慢性疼痛既是规训的后果，也是无声的抵抗；性别与流动身份共同构成资本积累的结构性基础。",
    "location": "Guangdong, Shenzhen",
    "countryOrRegion": "China",
    "lat": 22.5431,
    "lon": 114.0579,
    "sourceField": "中国 - 广东深圳",
    "locationEn": "China · Guangdong, Shenzhen"
  },
  {
    "id": "ethnography-41",
    "title": "《城市中的陌生人》(Strangers in the City)",
    "year": 2002,
    "author": "Li Zhang",
    "publisher": "Stanford",
    "summary": "中国城市化与市场化浪潮中，农村流动人口如何突破户籍制度限制，在北京形成大型移民社区并重组空间、权力与社会网络。\n\n以北京最大的流动人口社区为核心的详细民族志，追踪社区的建构、拆毁与重建过程。\n\n流动人口社区中的住房、市场空间和社会关系生产出非正式权力结构；后社会主义治理并非简单走向自由资本主义，而是在新的经济条件下重组国家与日常生活的关系。",
    "location": "Beijing, Zhejiangcun",
    "countryOrRegion": "China",
    "lat": 39.9042,
    "lon": 116.4074,
    "sourceField": "中国 - 北京浙江村",
    "locationEn": "China · Beijing, Zhejiangcun"
  },
  {
    "id": "ethnography-42",
    "title": "《跨越边界的社区》(Transcending Boundaries)",
    "year": 2005,
    "author": "Biao Xiang",
    "publisher": "Brill",
    "summary": "北京\"浙江村\"的温州移民如何自发建构跨越空间边界的商业网络与非正式社会秩序。\n\n多年深度田野调查结合中国民间关系网络与空间政治分析。\n\n民间社会具有强大的自我组织能力；移民社区的生存逻辑挑战了以国家为中心的发展与管治叙事。",
    "location": "Beijing, Zhejiangcun",
    "countryOrRegion": "China",
    "lat": 39.9042,
    "lon": 116.4074,
    "sourceField": "中国 - 北京浙江村",
    "locationEn": "China · Beijing, Zhejiangcun"
  },
  {
    "id": "ethnography-43",
    "title": "《治理教育欲望》(Governing Educational Desire)",
    "year": 2011,
    "author": "Andrew Kipnis",
    "publisher": "Chicago",
    "summary": "山东邹平的学生、家长与教师如何被国家与市场共同塑造出对教育成功的强烈渴望与自我规训冲动。\n\n中学与家庭的长期民族志调查结合政策文本分析。\n\n教育欲望并非自然本能，而是通过治理技术被生产出来；国家政策与市场逻辑在个体的教育焦虑中深度汇合。",
    "location": "Shandong, Zouping",
    "countryOrRegion": "China",
    "lat": 36.8628,
    "lon": 117.742,
    "sourceField": "中国 - 山东邹平",
    "locationEn": "China · Shandong, Zouping"
  },
  {
    "id": "ethnography-44",
    "title": "《信用的宇宙论》(Cosmologies of Credit)",
    "year": 2010,
    "author": "Julie Y. Chu",
    "publisher": "Duke",
    "summary": "福州长乐村民如何在蛇头、神明与亲属债务的多重信用宇宙论中构建出走海外的强烈意志与生命项目。\n\n长乐村落长期田野调查，追踪\"出发\"而非\"抵达\"的移民图景。\n\n移民不仅是经济理性选择，更是嵌入神圣债务与本体论可能性的宇宙论实践；离开本身即是一种存在论变迁。",
    "location": "Fujian, Fuzhou",
    "countryOrRegion": "China",
    "lat": 26.0745,
    "lon": 119.2965,
    "sourceField": "中国 - 福建福州",
    "locationEn": "China · Fujian, Fuzhou"
  },
  {
    "id": "ethnography-45",
    "title": "《另一种世界化》(Other-Worldly)",
    "year": 2009,
    "author": "Mei Zhan",
    "publisher": "Duke",
    "summary": "中医如何在上海与旧金山之间的跨国流通中，被重新组装为全球替代医学与中国现代性的双重象征。\n\n上海中医院与旧金山中医实践者的多点民族志调查。\n\n中医是\"另一种世界化\"的产物，既非传统的遗存，也非西方的他者；其跨国流通揭示了现代性本身的多元路径。",
    "location": "Shanghai / San Francisco",
    "countryOrRegion": "China / United States",
    "lat": 31.2304,
    "lon": 121.4737,
    "sourceField": "中国 - 上海 / 美国 - 旧金山",
    "locationEn": "China · Shanghai / United States · San Francisco",
    "sites": [
      {
        "lat": 31.2304,
        "lon": 121.4737
      },
      {
        "lat": 37.7749,
        "lon": -122.4194
      }
    ]
  },
  {
    "id": "ethnography-46",
    "title": "《不确定的爱》(Love's Uncertainty)",
    "year": 2015,
    "author": "Teresa Kuan",
    "publisher": "UC Press",
    "summary": "昆明城市中产家庭如何在\"提升人口素质\"的国家话语下，调和爱的伦理理想与激烈教育竞争的现实压力。\n\n城市家庭长期民族志调查，结合育儿手册、电视剧及政策文本的综合分析。\n\n爱的实践深嵌于国家话语与个人伦理的张力之中。",
    "location": "Yunnan, Kunming",
    "countryOrRegion": "China",
    "lat": 25.0389,
    "lon": 102.7183,
    "sourceField": "中国 - 云南昆明",
    "locationEn": "China · Yunnan, Kunming"
  },
  {
    "id": "ethnography-47",
    "title": "《当代中国农村的卫生、社会性和文化》(Hygiene, Sociality, and Culture in Contemporary Rural China)",
    "year": 2016,
    "author": "Lili Lai",
    "publisher": "Amsterdam",
    "summary": "\"新农村\"改造运动将\"卫生\"建构为衡量农村现代化程度的核心标准，并以此再生产城乡等级。\n\n河南农村长期田野调查结合政策文本与地方日常实践分析。\n\n卫生话语将农村贫困归因于农民的文化落后，掩盖了结构性不平等；国家治理的责任被转嫁为个体卫生习惯的道德问题。",
    "location": "Henan Province, Rural Villages",
    "countryOrRegion": "China",
    "lat": 34.7657,
    "lon": 113.7536,
    "sourceField": "中国 - 河南农村",
    "locationEn": "China · Henan Province, Rural Villages"
  },
  {
    "id": "ethnography-48",
    "title": "《世界中心的贫民窟》(Ghetto at the Center of the World)",
    "year": 2011,
    "author": "Gordon Mathews",
    "publisher": "Chicago",
    "summary": "重庆大厦作为世界各地低端全球化贸易商（南亚、非洲商人）聚集的多族裔生存空间与非正式经济节点。\n\n建筑内多语种长期参与观察与网络贸易链追踪。\n\n低端全球化是全球资本主义的另一面；重庆大厦揭示主权边界之间的非正式跨国流通秩序。",
    "location": "Hong Kong, Chungking Mansions",
    "countryOrRegion": "China",
    "lat": 22.2964,
    "lon": 114.1722,
    "sourceField": "中国 - 香港重庆大厦",
    "locationEn": "China · Hong Kong, Chungking Mansions"
  },
  {
    "id": "ethnography-49",
    "title": "《跨国灰姑娘》(Global Cinderellas)",
    "year": 2006,
    "author": "Pei-Chia Lan",
    "publisher": "Duke",
    "summary": "台湾新兴富裕家庭中，来自菲律宾与印尼的外籍女佣如何在雇主权威与自我尊严之间维系日常关系。\n\n家庭民族志与雇主及外佣的深度访谈，结合移工中介机构跟踪研究。\n\n全球化家务劳动中的阶级与种族不平等通过情感规训与空间管控被再生产；跨国灰姑娘的生存经验揭示全球照护链的结构性矛盾。",
    "location": "Taipei",
    "countryOrRegion": "Taiwan",
    "lat": 25.033,
    "lon": 121.5654,
    "sourceField": "台湾 - 台北",
    "locationEn": "Taiwan · Taipei"
  },
  {
    "id": "ethnography-50",
    "title": "《灵魂的障碍》(A Disability of the Soul)",
    "year": 2013,
    "author": "Karen Nakamura",
    "publisher": "Cornell",
    "summary": "日本北海道浦河町\"Bethel House\"——一个由精神分裂症患者自主管理的另类社区——中成员的日常生活与集体身份认同。\n\n社区长期参与观察，结合生命故事访谈与两部纪录片的视觉民族志。\n\n精神疾病是社会与文化的构建；Bethel House 的社区康复模式展示了去机构化与病患自我赋权的另一种可能。",
    "location": "Hokkaido, Urakawa, Bethel House",
    "countryOrRegion": "Japan",
    "lat": 42.1681,
    "lon": 142.7684,
    "sourceField": "日本 - 北海道浦河町",
    "locationEn": "Japan · Hokkaido, Urakawa, Bethel House"
  },
  {
    "id": "ethnography-51",
    "title": "《日本的抑郁症》(Depression in Japan)",
    "year": 2012,
    "author": "Junko Kitanaka",
    "publisher": "Princeton",
    "summary": "日本职场文化与精神病学话语如何共同将抑郁症建构为一种社会性苦难，进而引发大规模诊断与用药热潮。\n\n精神科诊所与职场田野调查结合精神病学史与药物推广档案分析。\n\n抑郁症在日本的流行不仅是医学事件，更是社会危机的症候；精神病学的扩张重塑了日本人对工作、苦难与自我的理解。",
    "location": "Tokyo",
    "countryOrRegion": "Japan",
    "lat": 35.6762,
    "lon": 139.6503,
    "sourceField": "日本 - 东京",
    "locationEn": "Japan · Tokyo"
  },
  {
    "id": "ethnography-52",
    "title": "《筑地》(Tsukiji)",
    "year": 2004,
    "author": "Theodore C. Bestor",
    "publisher": "UC Press",
    "summary": "东京筑地鱼市场作为世界最大海鲜交易枢纽，其商人文化、拍卖仪式与全球商品链的运作逻辑。\n\n市场长期参与观察，结合商人网络访谈与全球金枪鱼贸易链追踪。\n\n筑地不仅是经济场所，更是日本商人传统与全球资本主义相互嵌套的文化节点；地方饮食文化通过市场参与全球化进程。",
    "location": "Tokyo, Tsukiji Market",
    "countryOrRegion": "Japan",
    "lat": 35.6655,
    "lon": 139.7707,
    "sourceField": "日本 - 东京筑地市场",
    "locationEn": "Japan · Tokyo, Tsukiji Market"
  },
  {
    "id": "ethnography-53",
    "title": "《治愈劳动》(Healing Labor)",
    "year": 2020,
    "author": "Gabriele Koch",
    "publisher": "Stanford",
    "summary": "东京性产业中的日本女性从业者如何将性工作理解为一种女性化的照护劳动，并在此框架中构建职业认同。\n\n与东京性工作者长期田野访谈，结合日本性别劳动政治经济学分析。\n\n性被女性从业者理解为维系男性身心健康的\"治愈劳动\"；这一框架揭示性别化劳动分工与日本经济体制之间的深层连接。",
    "location": "Tokyo",
    "countryOrRegion": "Japan",
    "lat": 35.6762,
    "lon": 139.6503,
    "sourceField": "日本 - 东京",
    "locationEn": "Japan · Tokyo"
  },
  {
    "id": "ethnography-54",
    "title": "《千禧年的怪物》(Millennial Monsters)",
    "year": 2006,
    "author": "Anne Allison",
    "publisher": "UC Press",
    "summary": "日本电子游戏、动漫与玩具如何在全球流通中将日本\"酷文化\"建构为新型帝国软实力与商品拜物教。\n\n玩具产业、消费者文化与全球营销实践的多点民族志研究。\n\n\"神奇宝贝\"等怪兽商品将孤独与技术焦虑转化为消费欲望；日本流行文化在全球化中构建了一种千禧年资本主义的新型主体。",
    "location": "Tokyo (& Global Markets)",
    "countryOrRegion": "Japan",
    "lat": 35.6762,
    "lon": 139.6503,
    "sourceField": "日本 - 东京（及全球市场）",
    "locationEn": "Japan · Tokyo (& Global Markets)"
  },
  {
    "id": "ethnography-55",
    "title": "《亲密的分离》(Intimate Disconnections)",
    "year": 2020,
    "author": "Allison Alexy",
    "publisher": "Chicago",
    "summary": "当代日本离婚率上升背景下，离婚者——尤其是女性——如何将离婚重新叙述为寻求自主与个人成长的积极选择。\n\n东京离婚者的长期访谈与日本婚姻咨询机构田野调查。\n\n离婚在日本从道德失败被重新框架为个体独立的浪漫叙事；这一转变折射出新自由主义情感政治对私人生活的深层渗透。",
    "location": "Tokyo",
    "countryOrRegion": "Japan",
    "lat": 35.6762,
    "lon": 139.6503,
    "sourceField": "日本 - 东京",
    "locationEn": "Japan · Tokyo"
  },
  {
    "id": "ethnography-56",
    "title": "《被收养的领地》(Adopted Territory)",
    "year": 2010,
    "author": "Eleana Kim",
    "publisher": "Duke",
    "summary": "跨国韩裔领养者如何在韩国官方民族主义与西方领养家庭之间协商归属感与身份认同。\n\n首尔\"寻根之旅\"项目与海外韩裔领养者社群的多点民族志调查。\n\n跨国领养将儿童卷入国家民族主义、种族政治与全球化情感市场；领养者的\"被领养领地\"揭示公民身份与血缘归属的内在矛盾。",
    "location": "Seoul (& Overseas Korean Adoptee Communities)",
    "countryOrRegion": "South Korea",
    "lat": 37.5665,
    "lon": 126.978,
    "sourceField": "韩国 - 首尔（及海外韩裔领养者社群）",
    "locationEn": "South Korea · Seoul (& Overseas Korean Adoptee Communities)"
  },
  {
    "id": "ethnography-57",
    "title": "《债务危机中的韩国人》(South Koreans in the Debt Crisis)",
    "year": 2009,
    "author": "Jesook Song",
    "publisher": "Duke",
    "summary": "1997年亚洲金融危机后，韩国国家如何通过重构失业、福利与家庭话语，将新自由主义逻辑内化为公民美德。\n\n首尔政府福利机构与无家可归者安置点的田野调查结合政策文本分析。\n\n债务危机催生了新型\"新自由主义福利社会\"；国家将经济失败归咎于个体，而非结构性不平等，将自我管理转化为爱国责任。",
    "location": "Seoul",
    "countryOrRegion": "South Korea",
    "lat": 37.5665,
    "lon": 126.978,
    "sourceField": "韩国 - 首尔",
    "locationEn": "South Korea · Seoul"
  },
  {
    "id": "ethnography-58",
    "title": "《为爱而行》(On the Move for Love)",
    "year": 2010,
    "author": "Sealing Cheng",
    "publisher": "Pennsylvania",
    "summary": "菲律宾女性娱乐工作者如何在韩国美军基地周边的基地村中，在合法边界与情感劳动之间寻求尊严与出路。\n\n基地村长期参与观察与菲律宾女性工作者深度访谈。\n\n情感劳动与性工作在军事驻留的地缘政治框架下被性别化与种族化；女性的迁移不仅是经济决策，更是爱与主体性的实践。",
    "location": "Dongducheon, US Military Camptown",
    "countryOrRegion": "South Korea",
    "lat": 37.9036,
    "lon": 127.0606,
    "sourceField": "韩国 - 东豆川 美军基地周边",
    "locationEn": "South Korea · Dongducheon, US Military Camptown"
  },
  {
    "id": "ethnography-59",
    "title": "《野鬼的时代》(The Age of Wild Ghosts)",
    "year": 2001,
    "author": "Erick Mueggler",
    "publisher": "UC Press",
    "summary": "云南彝族村民如何通过仪式与鬼魂叙事，应对遗留的创伤记忆。\n\n长期村落田野调查，结合仪式文本与口述史。\n\n历史暴力以鬼魂的形式栖居于地景之中；暴力的记忆只能在国家叙事之外的仪式领域中被迂回表达与处理。",
    "location": "Yunnan, Yi People (Lufeng County)",
    "countryOrRegion": "China",
    "lat": 25.15,
    "lon": 102.08,
    "sourceField": "中国 - 云南彝族（禄丰县）",
    "locationEn": "China · Yunnan, Yi People (Lufeng County)"
  },
  {
    "id": "ethnography-60",
    "title": "《纸路》(The Paper Road)",
    "year": 2011,
    "author": "Erick Mueggler",
    "publisher": "UC Press",
    "summary": "十九至二十世纪西方植物学家在云南与西藏的采集活动，如何在档案、标本与地方记忆中留下相互矛盾的痕迹。\n\n档案研究与沿原路线的当代民族志重走相结合。\n\n博物学档案是帝国知识生产的遗留物；将档案与身体经验并置，揭示科学探索的多重时间性与殖民暴力。",
    "location": "Yunnan / Tibet (Botanical Expedition Routes)",
    "countryOrRegion": "China",
    "lat": 29.65,
    "lon": 91.1,
    "sourceField": "中国 - 云南 / 西藏",
    "locationEn": "China · Yunnan / Tibet (Botanical Expedition Routes)",
    "sites": [
      {
        "lat": 29.65,
        "lon": 91.1
      }
    ]
  },
  {
    "id": "ethnography-61",
    "title": "《逝者悼歌》(Songs for Dead Parents)",
    "year": 2017,
    "author": "Erick Mueggler",
    "publisher": "Chicago",
    "summary": "彝族丧礼中吟诵的哀歌如何在文本、尸体与宇宙秩序之间构建死亡与过渡的意义。\n\n丧礼仪式的长期参与观察与仪式文本的语言学精读分析。\n\n语言不只是描述世界，而是在仪式表演中主动制造新的存在形态；哀歌的表演性言说重组了人、鬼与神的关系格局。",
    "location": "Yunnan, Yi People (Lufeng County)",
    "countryOrRegion": "China",
    "lat": 25.15,
    "lon": 102.08,
    "sourceField": "中国 - 云南彝族（禄丰县）",
    "locationEn": "China · Yunnan, Yi People (Lufeng County)"
  },
  {
    "id": "ethnography-62",
    "title": "《我的凉山兄弟》(Passage to Manhood)",
    "year": 2011,
    "author": "Shao-hua Liu（刘绍华）",
    "publisher": "Stanford",
    "summary": "凉山彝族（诺苏）青年男性如何在改革开放后的流动与城乡落差中，陷入海洛因成瘾与艾滋病的双重困境。\n\n凉山彝族社区长期田野调查，追踪青年迁徙轨迹与吸毒网络。\n\n成瘾不是道德失败，而是现代化进程中少数民族青年被边缘化的结构性后果；国家防艾项目未能触及成瘾的社会根源。",
    "location": "Sichuan, Liangshan Yi (Nuosu) Territory",
    "countryOrRegion": "China",
    "lat": 27.8945,
    "lon": 102.2644,
    "sourceField": "中国 - 四川省 凉山 彝族（诺苏）地区",
    "locationEn": "China · Sichuan, Liangshan Yi (Nuosu) Territory"
  },
  {
    "id": "ethnography-63",
    "title": "《成为克钦》(Being and Becoming Kachin)",
    "year": 2013,
    "author": "Mandy Sadan",
    "publisher": "Oxford",
    "summary": "克钦人如何在缅甸国家、殖民历史与跨境网络中建构动态的族群认同与地方历史叙事。\n\n克钦邦田野调查结合英国殖民档案与多族群口述史。\n\n族群性不是固定本质，而是在边界地带的历史遭遇中持续被制造和争夺；赞米亚的\"逃避国家\"逻辑需以具体历史过程加以修正。",
    "location": "Kachin State (China-Myanmar Borderlands)",
    "countryOrRegion": "Myanmar",
    "lat": 25.3836,
    "lon": 97.3964,
    "sourceField": "缅甸 - 克钦邦（中缅边境地带）",
    "locationEn": "Myanmar · Kachin State (China-Myanmar Borderlands)"
  },
  {
    "id": "ethnography-64",
    "title": "《勉族关系》(Mien Relations)",
    "year": 2005,
    "author": "Hjorleifur Jonsson",
    "publisher": "Cornell",
    "summary": "泰国清莱勉族如何在国家整合、发展计划与跨境离散网络中维持自身文化实践与社会关系。\n\n泰国北部山地长期田野调查，结合历史人口档案与跨境网络追踪。\n\n山地族群与低地国家的关系并非单向同化，而是持续的双向谈判；勉族的族群关系策略是一种有意识的主权协商实践。",
    "location": "Chiang Rai, Mien (Yao) Highland Communities",
    "countryOrRegion": "Thailand",
    "lat": 19.9105,
    "lon": 99.8406,
    "sourceField": "泰国 - 清莱省勉（瑶）族山地社区",
    "locationEn": "Thailand · Chiang Rai, Mien (Yao) Highland Communities"
  },
  {
    "id": "ethnography-65",
    "title": "《他者之社会》(Society of Others)",
    "year": 2009,
    "author": "Rupert Stasch",
    "publisher": "UC Press",
    "summary": "科罗瓦伊人如何将\"他异性\"作为社会关系的核心原则，通过陌生感构建亲属与哀悼的意义。\n\n两年深度田野调查，结合语言学与仪式分析。\n\n社会关系的基础不是同一性而是差异；美拉尼西亚社会的他者关系理论对西方人类学亲属理论构成根本性挑战。",
    "location": "West Papua, Korowai Territory (Melanesia)",
    "countryOrRegion": "Indonesia",
    "lat": -5.55,
    "lon": 140.45,
    "sourceField": "印度尼西亚 - 西巴布亚科罗瓦伊地区",
    "locationEn": "Indonesia · West Papua, Korowai Territory (Melanesia)"
  },
  {
    "id": "ethnography-67",
    "title": "《逆向人类学》(Reverse Anthropology)",
    "year": 2006,
    "author": "Stuart Kirsch",
    "publisher": "Stanford",
    "summary": "奥克特迪铜矿污染引发的原住民环境运动，以及原住民如何以自身分析框架理解和应对采矿资本主义。\n\n长期田野调查结合法律诉讼档案与环境运动跟踪。\n\n原住民社会分析具有独立的认识论效力；\"逆向人类学\"要求研究者承认被研究者同样在分析我们的世界。",
    "location": "Ok Tedi Mining Area, Western Province",
    "countryOrRegion": "Papua New Guinea",
    "lat": -5.27,
    "lon": 141.23,
    "sourceField": "巴布亚新几内亚 - 西巴布亚奥克特迪矿区",
    "locationEn": "Papua New Guinea · Ok Tedi Mining Area, Western Province"
  },
  {
    "id": "ethnography-68",
    "title": "《在全球的边缘》(On the Edge of the Global)",
    "year": 2011,
    "author": "Niko Besnier",
    "publisher": "Stanford",
    "summary": "汤加人在全球化、移民压力与本土身份认同之间产生的现代性焦虑与道德危机感。\n\n汤加群岛多社区田野调查，结合海外侨民网络与媒体研究。\n\n太平洋岛民并非全球化的被动接受者，而是在移动与根植之间艰难维持主体性的现代主体；焦虑本身是结构性的。",
    "location": "Tongatapu / Tongan Islands (Polynesia)",
    "countryOrRegion": "Tonga",
    "lat": -21.18,
    "lon": -175.2,
    "sourceField": "汤加 - 汤加群岛",
    "locationEn": "Tonga · Tongatapu / Tongan Islands (Polynesia)",
    "sites": [
      {
        "lat": -21.18,
        "lon": -175.2
      },
      {
        "lat": -18.65,
        "lon": -173.98
      }
    ]
  },
  {
    "id": "ethnography-69",
    "title": "《金矿上的利维坦》(Leviathans at the Gold Mine)",
    "year": 2014,
    "author": "Alex Golub",
    "publisher": "Duke",
    "summary": "巴布亚新几内亚伊皮利人与跨国金矿公司如何在谈判、冲突与法律程序中相互塑造对方的主体形态。\n\n矿区长期田野调查结合企业文件与法律档案分析。\n\n公司与原住民群体都不是预先存在的固定实体，而是在资源开发的政治过程中相互构成的行动者。",
    "location": "Porgera Gold Mine, Enga Province",
    "countryOrRegion": "Papua New Guinea",
    "lat": -5.46,
    "lon": 143.12,
    "sourceField": "巴布亚新几内亚 - 波尔盖拉金矿区",
    "locationEn": "Papua New Guinea · Porgera Gold Mine, Enga Province"
  },
  {
    "id": "ethnography-70",
    "title": "《礼物的性别》(The Gender of Gift)",
    "year": 1988,
    "author": "Marilyn Strathern",
    "publisher": "UC Press",
    "summary": "美拉尼西亚社会中礼物交换的性别逻辑：女性并非交换的主体，而是被纳入男性礼物网络的媒介与对象。\n\n跨美拉尼西亚比较民族志与象征人类学理论综合分析。\n\n\"礼物\"范畴不能被移植于美拉尼西亚；性别在此不是社会身份，而是关系转换的媒介。",
    "location": "Mt. Hagen Area, Western Highlands",
    "countryOrRegion": "Papua New Guinea",
    "lat": -5.86,
    "lon": 144.23,
    "sourceField": "巴布亚新几内亚 - 美拉尼西亚高地（哈根山区）",
    "locationEn": "Papua New Guinea · Mt. Hagen Area, Western Highlands"
  },
  {
    "id": "ethnography-71",
    "title": "《廉价的肉》(Cheap Meat)",
    "year": 2010,
    "author": "D. Gewertz & F. Errington",
    "publisher": "UC Press",
    "summary": "廉价羊排边角料（flap）从澳新生产商到太平洋岛国消费者之间的商品链，以及其如何加剧当地肥胖与健康危机。\n\n多点商品链民族志，追踪廉价肉类从生产、出口到消费的全程。\n\n全球食品贸易中的不平等并非偶然：富国的边角废料以\"廉价\"之名转化为穷国的饮食主流，将结构性暴力铭刻于身体之中。",
    "location": "Tonga",
    "countryOrRegion": "Pacific Island Nations",
    "lat": -21.18,
    "lon": -175.2,
    "sourceField": "太平洋岛国 - 汤加",
    "locationEn": "Pacific Island Nations · Tonga",
    "sites": [
      {
        "lat": -21.18,
        "lon": -175.2
      }
    ]
  }
];
